void get_screen_specs(void);
void clear_screen(void);
void draw_box(int, int, short int);
void draw_empty_x(int,int);
void plot_pixel(int, int, short int);
void draw_line(int, int, int, int, int);
void wait_for_vsync(void);
void erase_line(int, int, int, int);
void initializer();
void erase_box(int, int);
void erase_basket(int,int);
void draw_basket(int, int);
void draw_fruit(int, int, int, int, int*);
void erase_fruit(int, int, int, int);
void config_timer(void);
void draw_text(int, int, char*);
void draw_game_over(void);
void draw_red_x(int, int);
void display_HEX(int);
void draw_start_page(void);
void replace_survival(int, int);
void replace_fruit_fren(int, int);
void replace_main_menu(int, int);
void replace_leader_board(int, int);
void audio_playback_mono(int*, int, int);
void erase_all_text(void);
void interrupt_handler(void);
void KEY_ISR(void);